import { Category, Post } from "./types/collection";

export const DUMMY_POST: Post[] = [
  {
    id: "1",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "Cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://images.unsplash.com/photo-1575936123452-b67c3203c357?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "Cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://images.unsplash.com/photo-1575936123452-b67c3203c357?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
  {
    id: "3",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "Cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://images.unsplash.com/photo-1575936123452-b67c3203c357?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
  {
    id: "4",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "Cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://images.unsplash.com/photo-1575936123452-b67c3203c357?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
  {
    id: "5",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "Cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://images.unsplash.com/photo-1575936123452-b67c3203c357?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
];

export const DUMMY_CATEGORY: Category[] = [
  {
    id: "1",
    title: "Cities",
    slug: "cities",
    description: "cities and cities in the database",
  },
  {
    id: "2",
    title: "Experience",
    slug: "Experience",
    description: "cities and cities in the database",
  },
];
