import { Category, Post } from "./types/collection";

export const DUMMY_POST: Post[] = [
  {
    id: "1",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://www.google.com.vn/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fimage&psig=AOvVaw1jK3Uwfq0q7Xxbp866ZlDE&ust=1696589549810000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKDVid3e3oEDFQAAAAAdAAAAABAE",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://www.google.com.vn/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fimage&psig=AOvVaw1jK3Uwfq0q7Xxbp866ZlDE&ust=1696589549810000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKDVid3e3oEDFQAAAAAdAAAAABAE",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
  {
    id: "3",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://www.google.com.vn/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fimage&psig=AOvVaw1jK3Uwfq0q7Xxbp866ZlDE&ust=1696589549810000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKDVid3e3oEDFQAAAAAdAAAAABAE",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
  {
    id: "4",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://www.google.com.vn/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fimage&psig=AOvVaw1jK3Uwfq0q7Xxbp866ZlDE&ust=1696589549810000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKDVid3e3oEDFQAAAAAdAAAAABAE",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
  {
    id: "5",
    title: "lorem ipsum dolor sit amet",
    description: "lorem ipsum dolor sit amet in rep another dolor sit",
    category: {
      id: "1",
      title: "cities",
    },
    author: {
      id: "1",
      first_name: "John",
      last_name: "John",
    },
    slug: "lorem dw signatures of the cities of the cities of the cities of the cities of the cities of the",
    image:
      "https://www.google.com.vn/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fimage&psig=AOvVaw1jK3Uwfq0q7Xxbp866ZlDE&ust=1696589549810000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKDVid3e3oEDFQAAAAAdAAAAABAE",
    body: "dw qwd xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxxxxxxxx xxxxxxxxx",
    date_created: "2000-01-01T00:00:00Z",
    date_updated: "2000-01-01T00:00:00Z",
  },
];

export const DUMMY_CATEGORY: Category[] = [
  {
    id: "1",
    title: "Cities",
    slug: "cities",
    description: "cities and cities in the database",
  },
  {
    id: "2",
    title: "Experience",
    slug: "Experience",
    description: "cities and cities in the database",
  },
];
